BOT:
  OWNERS: ["1304080189029875753","1437338367204261931"]
  ADMINS: ["1304080189029875753","1437338367204261931"]
  TOPGG_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfdCI6Ijc4MzU3ODY3MTg3ODQ2MzQ4OCIsImlkIjoiNzgyNTk1MTM4MjIyMzQyMTQ0IiwiaWF0IjoxNzY0NjU2NTEzfQ.O56mEb1svrx1OghZKPM2FottfgKl-QriZ0irrxvzneM"

LINKS:
  SUPPORT: "https://discord.gg/uskTjqz5ah"

SPOTIFY:
  ID: "b3bbb44982aa4d098f0dcfaf73f9de19"
  SECRET: "273f1d5d2640475097d46482908a73ce"

LAVALINK:
  HOST: "lavalink.jirayu.net"
  PORT: 13592
  AUTH: "youshallnotpass"
  SECURE: false
  NAME: "main"

Chiku:
  PREFIX: "!"
  EMOJIS: "black"
  CLIENT_ID: "1500425524009500802"
  TOKEN: "MTUwMDQyNTUyNDAwOTUwMDgwMg.G_NRML.iqgIh0AVdSfWBQQu0XZdZdJqzZ0SyP6Se5E3ew"

Mimi:
  PREFIX: "!"
  EMOJIS: "black"
  SHARDS: "auto"
  PER_CLUSTER: 4
  CLIENT_ID: "1500425524009500802"
  CLIENT_SECRET: "2ypqHG7PiVX800iNknGd1KPxN8VVt1uP"
  TOKEN: "MTUwMDQyNTUyNDAwOTUwMDgwMg.G_NRML.iqgIh0AVdSfWBQQu0XZdZdJqzZ0SyP6Se5E3ew"

WEBHOOKS:
  ERROR: "https://discord.com/api/webhooks/1540217507002974281/t3euutb9_HCV0iLaCf1Wr4c2xVmJmtqGdCSO8Bs1_Cxy0pyVYkRxuIpToLvPknT6pNoq"
  STATIC: "https://discord.com/api/webhooks/1540217507002974281/t3euutb9_HCV0iLaCf1Wr4c2xVmJmtqGdCSO8Bs1_Cxy0pyVYkRxuIpToLvPknT6pNoq"
  SERVER: "https://discord.com/api/webhooks/1540217507002974281/t3euutb9_HCV0iLaCf1Wr4c2xVmJmtqGdCSO8Bs1_Cxy0pyVYkRxuIpToLvPknT6pNoq"
  COMMAND: "https://discord.com/api/webhooks/1540217507002974281/t3euutb9_HCV0iLaCf1Wr4c2xVmJmtqGdCSO8Bs1_Cxy0pyVYkRxuIpToLvPknT6pNoq"

DATABASE:
  MONGODB_URI: "mongodb+srv://r3ag6:irk2y@cluster0.faljdmg.mongodb.net/Chiku?retryWrites=true&w=majority"

DASHBOARD:
  ENABLED: true
  PORT: 25913
  API_KEY: "dd486359d561db6badfad26868d718b82220fb63bf63329517e886530d1078e0"
  ALLOWED_ORIGIN: "https://chikubot.vercel.app"
